[package]
name = "infrastructure-db"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crates-core-domain = { path = "../../domain" }
core-errors = { path = "../../core/errors" }

actix-web.workspace = true
askama.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
ulid.workspace = true

sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
