[package]
name = "infra"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[features]
default     = []
infrastructure-db          = ["dep:infrastructure-db"]
infrastructure-cache       = ["dep:infrastructure-cache"]
infrastructure-email       = ["dep:infrastructure-email"]
infrastructure-jwt         = ["dep:infrastructure-jwt"]
infrastructure-metrics     = ["dep:infrastructure-metrics"]
infrastructure-oauth       = ["dep:infrastructure-oauth"]
infrastructure-payment     = ["dep:infrastructure-payment"]
infrastructure-pwd         = ["dep:infrastructure-pwd"]
infrastructure-queue       = ["dep:infrastructure-queue"]
infrastructure-ratelimit   = ["dep:infrastructure-ratelimit"]
infrastructure-session     = ["dep:infrastructure-session"]
infrastructure-storage     = ["dep:infrastructure-storage"]

[dependencies]
infrastructure-cache     = { path = "./cache",     optional = true }
infrastructure-db        = { path = "./db",        optional = true }
infrastructure-email     = { path = "./email",     optional = true }
infrastructure-jwt       = { path = "./jwt",       optional = true }
infrastructure-metrics   = { path = "./metrics",   optional = true }
infrastructure-oauth     = { path = "./oauth",     optional = true }
infrastructure-payment   = { path = "./payment",   optional = true }
infrastructure-pwd       = { path = "./pwd",       optional = true }
infrastructure-queue     = { path = "./queue",     optional = true }
infrastructure-ratelimit = { path = "./ratelimit", optional = true }
infrastructure-session   = { path = "./session",   optional = true }
infrastructure-storage   = { path = "./storage",   optional = true }

