[package]
name = "rsync_maang"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[dependencies]
dirs.workspace = true
time.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
