[workspace]
resolver = "3"

members = [
  "apps/*",
  "crates/application",
  "crates/application/api",
  "crates/application/cli",
  "crates/application/web",
  "crates/core",
  "crates/core/config",
  "crates/core/errors",
  "crates/core/observability",
  "crates/core/utils",
  "crates/domain",
  "crates/domain/users",
  "crates/domain/tenants",
  "crates/domain/products",
  "crates/domain/services",
  "crates/domain/media",
  "crates/infra",
  "crates/infra/cache",
  "crates/infra/db",
  "crates/infra/email",
  "crates/infra/jwt",
  "crates/infra/metrics",
  "crates/infra/oauth",
  "crates/infra/payment",
  "crates/infra/pwd",
  "crates/infra/queue",
  "crates/infra/ratelimit",
  "crates/infra/session",
  "crates/infra/storage",
  "crates/application/web",
  "tools/*"
]

# You can drop the 'exclude' workaround entirely with this approach.

exclude = [
  "target","dist","bench","backups","data","wip","tests/load"
]

default-members = ["apps/lillpepe"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.81"
version = "0.1.0"

[workspace.dependencies]
actix-web = "4.9"
askama = "0.14.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.17"
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ulid = "1.1"
uuid = { version = "1", features = ["v4", "serde"] }


[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
expect_used = "deny"
panic = "deny"
unused_crate_dependencies = "deny"
unwrap_used = "deny"

