[package]
name = "core-observability"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
actix-web.workspace = true
askama.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3.20"
ulid.workspace = true

[lints]
workspace = true

