[package]
name = "application-web"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

build = "build.rs"

[dependencies]
core-config.workspace = true

actix-files.workspace = true
actix-web.workspace = true
askama.workspace = true
rand.workspace = true
redis.workspace = true
serde.workspace = true
time.workspace = true
tracing.workspace = true

[build-dependencies]
time.workspace = true

[lints]
workspace = true



