[package]
name = "infrastructure-queue"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
actix-web.workspace = true
askama.workspace = true
serde.workspace = true
thiserror.workspace = true
lints.workspace = true
tracing.workspace = true
ulid.workspace = true


