[package]
name = "application"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
domain = { path = "../domain" }
core = { path = "../core" }

core-domain-errors = { path = "../core/errors" }
core-observability = { path = "../core/observability" }

actix-web.workspace = true
askama.workspace = true
serde.workspace = true
thiserror.workspace = true
lints.workspace = true
tracing.workspace = true
ulid.workspace = true

