[package]
name = "core-errors"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true


[dependencies]
actix-web.workspace = true
askama.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
ulid.workspace = true

[lints]
workspace = true


