[package]
name = "domain"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[dependencies]
core-errors = { path = "../core/errors" }

actix-web.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true


